spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: wangwei521
    url: jdbc:mysql://localhost/msg-dev?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true

  server:
    port: 8080
